services:
  postgres-dbmeli:
    image: postgres:13.3
    container_name: postgres-dbmeli
    environment:
      POSTGRES_DB: meli_db
      POSTGRES_USER: meli
      POSTGRES_PASSWORD: "#M7h2c829"
    volumes:
      - postgres-dbmeli:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - pgnetwork-dbmeli

  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dbmeli:5432/meli_db
      SPRING_DATASOURCE_USERNAME: meli
      SPRING_DATASOURCE_PASSWORD: "#M7h2c829"
    networks:
      - pgnetwork-dbmeli

volumes:
  postgres-dbmeli: {}

networks:
  pgnetwork-dbmeli: {}