spring.profiles.active=dev
server.port=8081
spring.application.name=meli
spring.datasource.url=jdbc:postgresql://localhost:5432/meli_db
spring.datasource.username=meli
spring.datasource.password=#M7h2c829
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

## MESSAGES
srping.messages.basename=messages
spring.messages.encoding=UTF-8

## FLYWAY
spring.flyway.enabled=false
